import { DutyPoint, EmployeeDirectoryItem, Holiday, Personnel, Settings, UserAccount } from './types';

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'USR001',
    username: 'admin',
    password: 'password123',
    name: 'ผู้ดูแลระบบสูงสุด (Super Admin)',
    role: 'superadmin',
    status: 'active',
    createdAt: '2026-01-01',
    lastLogin: '2026-08-28 08:30',
  },
  {
    id: 'USR002',
    username: 'officer1',
    password: 'password123',
    name: 'เจ้าหน้าที่งานธุรการ (Admin)',
    role: 'admin',
    status: 'active',
    createdAt: '2026-01-15',
    lastLogin: '2026-08-27 16:45',
  },
  {
    id: 'USR003',
    username: 'officer2',
    password: 'password123',
    name: 'เจ้าหน้าที่งานสารบรรณ (Officer)',
    role: 'officer',
    status: 'active',
    createdAt: '2026-02-01',
    lastLogin: '2026-08-25 10:15',
  },
];

export const DEFAULT_SETTINGS: Settings = {
  malePoints: 4,
  femalePoints: 3,
  headPerPoint: 1,
  subPerPoint: 1,
  appsScriptUrl: 'https://script.google.com/macros/s/AKfycbw0uBAjnDuP7zKLQ3OzpvrslxsTfaz9misMR7zsTHVFnHioIULX4bKO3ELl5LeR3W_s/exec',
  adminPasscode: 'admin1234',
};

export const INITIAL_DUTY_POINTS: DutyPoint[] = [
  { id: 1, name: 'สำนักงานเทศบาล', gender: 'M', order_index: 1 },
  { id: 2, name: 'ศูนย์บริการสาธารณสุข แห่งที่ 2', gender: 'M', order_index: 2 },
  { id: 3, name: 'ศูนย์บริการสาธารณสุข แห่งที่ 3', gender: 'M', order_index: 3 },
  { id: 4, name: 'โครงการปรับปรุงคุณภาพน้ำ', gender: 'M', order_index: 4 },
  { id: 5, name: 'สำนักงานเทศบาล (กลางวัน)', gender: 'F', order_index: 1 },
  { id: 6, name: 'ศูนย์บริการสาธารณสุข แห่งที่ 2 (กลางวัน)', gender: 'F', order_index: 2 },
  { id: 7, name: 'ศูนย์บริการสาธารณสุข แห่งที่ 3 (กลางวัน)', gender: 'F', order_index: 3 },
];

export const INITIAL_HOLIDAYS: Holiday[] = [
  { id: 1, holiday_date: '2026-01-01', name: 'วันขึ้นปีใหม่', type: 'official' },
  { id: 2, holiday_date: '2026-03-03', name: 'วันมาฆบูชา', type: 'official' },
  { id: 3, holiday_date: '2026-04-06', name: 'วันพระบาทสมเด็จพระพุทธยอดฟ้าจุฬาโลกมหาราชและวันที่ระลึกมหาจักรีบรมราชวงศ์', type: 'official' },
  { id: 4, holiday_date: '2026-04-13', name: 'วันสงกรานต์', type: 'official' },
  { id: 5, holiday_date: '2026-04-14', name: 'วันสงกรานต์', type: 'official' },
  { id: 6, holiday_date: '2026-04-15', name: 'วันสงกรานต์', type: 'official' },
  { id: 7, holiday_date: '2026-05-01', name: 'วันแรงงานแห่งชาติ', type: 'official' },
  { id: 8, holiday_date: '2026-05-04', name: 'วันฉัตรมงคล', type: 'official' },
  { id: 9, holiday_date: '2026-05-31', name: 'วันวิสาขบูชา', type: 'official' },
  { id: 10, holiday_date: '2026-06-03', name: 'วันเฉลิมพระชนมพรรษาสมเด็จพระนางเจ้าฯ พระบรมราชินี', type: 'official' },
  { id: 11, holiday_date: '2026-07-28', name: 'วันเฉลิมพระชนมพรรษาพระบาทสมเด็จพระเจ้าอยู่หัว', type: 'official' },
  { id: 12, holiday_date: '2026-07-29', name: 'วันอาสาฬหบูชา', type: 'official' },
  { id: 13, holiday_date: '2026-07-30', name: 'วันเข้าพรรษา', type: 'official' },
  { id: 14, holiday_date: '2026-08-12', name: 'วันเฉลิมพระชนมพรรษาสมเด็จพระบรมราชชนนีพันปีหลวง และวันแม่แห่งชาติ', type: 'official' },
  { id: 15, holiday_date: '2026-10-13', name: 'วันนวมินทรมหาราช', type: 'official' },
  { id: 16, holiday_date: '2026-10-23', name: 'วันปิยมหาราช', type: 'official' },
  { id: 17, holiday_date: '2026-12-05', name: 'วันคล้ายวันพระบรมราชสมภพ รัชกาลที่ 9 / วันชาติ / วันพ่อแห่งชาติ', type: 'official' },
  { id: 18, holiday_date: '2026-12-10', name: 'วันรัฐธรรมนูญ', type: 'official' },
  { id: 19, holiday_date: '2026-12-31', name: 'วันสิ้นปี', type: 'official' },
];

function splitName(fullName: string): { fname: string; lname: string } {
  const parts = fullName.trim().split(/\s+/);
  if (parts.length <= 1) {
    return { fname: fullName.trim(), lname: '' };
  }
  return {
    fname: parts[0],
    lname: parts.slice(1).join(' '),
  };
}

const RAW_GUARD_DATA = [
  {"id":6,"employee_id":"4769","full_name":"นายอนุรักษ์ วิภูษิตสมบูรณ์","gender":"M","position":"หัวหน้าฝ่ายการโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783044204579},
  {"id":7,"employee_id":"4835","full_name":"นายศรัณยู คำสามารถ","gender":"M","position":"หัวหน้าฝ่ายบรรจุแต่งตั้งและอัตรากำลัง","department":"กองการเจ้าหน้าที่","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783044167384},
  {"id":8,"employee_id":"4804","full_name":"นายทรงยศ แสนทวีสุข","gender":"M","position":"หัวหน้าฝ่ายบริการและเผยแพร่วิชาการ","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783044219564},
  {"id":9,"employee_id":"4812","full_name":"นายพลกิตติวัฒ เกษมสิริอนันต์","gender":"M","position":"หัวหน้าฝ่ายบริหารการศึกษา","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783044230603},
  {"id":10,"employee_id":"4780","full_name":"นายสุทธิพงษ์ วงศ์ศิริ","gender":"M","position":"นายช่างเครื่องกล","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783044265931},
  {"id":11,"employee_id":"4831","full_name":"นายภูวนาท สุขประเสริฐ","gender":"M","position":"หัวหน้าฝ่ายบุคลากรทางการศึกษา","department":"กองการเจ้าหน้าที่","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783046270841},
  {"id":12,"employee_id":"4768","full_name":"นายคมกริช แก้วคูณ","gender":"M","position":"หัวหน้าฝ่ายแบบแผนและก่อสร้าง","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783046287327},
  {"id":13,"employee_id":"4750","full_name":"ว่าที่ร.ต.วิชิต หวังยศ","gender":"M","position":"นักจัดการงานเทศกิจ","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"1","orderIndex":1783046425468},
  {"id":14,"employee_id":"5779","full_name":"นายอภิชัย ศรีทอง","gender":"M","position":"ผู้ช่วยนายช่างโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"1","orderIndex":1783046459280},
  {"id":15,"employee_id":"4738","full_name":"นายปกรณ์ชัย เผิ่งจันดา","gender":"M","position":"นิติกร","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"2","orderIndex":1783046495964},
  {"id":16,"employee_id":"5713","full_name":"นายชลัท บุญยู้","gender":"M","position":"พนักงานขับรถยนต์","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"2","orderIndex":1783046651948},
  {"id":17,"employee_id":"4773","full_name":"นายณฐกานต์ พรมแก้ว","gender":"M","position":"วิศวกรโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"3","orderIndex":1783046859344},
  {"id":18,"employee_id":"5931","full_name":"นายเอกลักษณ์ เพ็งเกษม","gender":"M","position":"คนงาน","department":"กองช่างสุขาภิบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"3","orderIndex":1783046937904},
  {"id":19,"employee_id":"4818","full_name":"จ.ส.อ.สราวุฒิ แสงอุทัย","gender":"M","position":"เจ้าพนักงานธุรการ","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"4","orderIndex":1783047017316},
  {"id":20,"employee_id":"5760","full_name":"นายณัฐพล จงพิชิตชัยชนะ","gender":"M","position":"คนงาน","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"4","orderIndex":1783047038059},
  {"id":21,"employee_id":"4808","full_name":"นายภูษณ ฝักบัว","gender":"M","position":"นักวิชาการคอมพิวเตอร์","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"5","orderIndex":1783047145644},
  {"id":22,"employee_id":"5783","full_name":"นายเจษฎา ลิขิตบรรจงกุล","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"5","orderIndex":1783047179027},
  {"id":23,"employee_id":"4778","full_name":"นายประสิทธิ์ สีสัน","gender":"M","position":"นายช่างโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"6","orderIndex":1783047197447},
  {"id":24,"employee_id":"5735","full_name":"นายเจษฎา อยู่คง","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"6","orderIndex":1783047221312},
  {"id":25,"employee_id":"4774","full_name":"ว่าที่ร.ต.เกรียงไกร กองพันธ์","gender":"M","position":"นายช่างโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"7","orderIndex":1783047234255},
  {"id":27,"employee_id":"4816","full_name":"สิบเอกเผด็จ การินทร์","gender":"M","position":"นักวิชาการศึกษา","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"8","orderIndex":1783047271675},
  {"id":28,"employee_id":"5907","full_name":"นายวันชัย ชัยโยดม","gender":"M","position":"คนงาน","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"8","orderIndex":1783047310611},
  {"id":29,"employee_id":"4787","full_name":"นายสุรัตน์ เรือนเงิน","gender":"M","position":"เจ้าพนักงานธุรการ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"9","orderIndex":1783047338763},
  {"id":30,"employee_id":"5721","full_name":"นายฉัตรชัย จันทร์ไทย","gender":"M","position":"พนักงานดับเพลิง","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"9","orderIndex":1783047364347},
  {"id":31,"employee_id":"4817","full_name":"นายปฐวี ส่งเสริม","gender":"M","position":"นักวิชาการศึกษา","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"10","orderIndex":1783047383171},
  {"id":32,"employee_id":"5911","full_name":"นายทักษดนัย ไพศาล","gender":"M","position":"คนงาน","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"13","orderIndex":1783053791706},
  {"id":33,"employee_id":"4797","full_name":"นางธิปนาถ สุระพรรค","gender":"F","position":"พยาบาลวิชาชีพ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783050674345},
  {"id":34,"employee_id":"4753","full_name":"นางสาวนุชนาถ ดีสุภาพ","gender":"F","position":"หัวหน้าฝ่ายบริหารงานคลัง","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1787645708766},
  {"id":36,"employee_id":"4755","full_name":"นางสาวอัญญ์สิริญ กัญญาพันธ์","gender":"F","position":"หัวหน้าฝ่ายพัสดุและทรัพย์สิน","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783047991099},
  {"id":38,"employee_id":"4785","full_name":"นางพีระพิชญ์ รวมธรรม","gender":"F","position":"หัวหน้าฝ่ายบริหารงานสาธารณสุข","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783048020634},
  {"id":39,"employee_id":"4754","full_name":"นางชยาพร ไพศาล","gender":"F","position":"หัวหน้าฝ่ายพัฒนารายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783048038137},
  {"id":40,"employee_id":"4814","full_name":"นางสุวีณา นวลเนตร","gender":"F","position":"นักวิชาการคลัง","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"1","orderIndex":1783048188598},
  {"id":41,"employee_id":"5912","full_name":"นางสาวณัฐริกา สร้อยนาค","gender":"F","position":"คนงาน","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"1","orderIndex":1783048235409},
  {"id":42,"employee_id":"4826","full_name":"นางสาวพรวิภา ศรียาภัย","gender":"F","position":"นักพัฒนาชุมชน","department":"กองสวัสดิการสังคม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"2","orderIndex":1783048280913},
  {"id":43,"employee_id":"5753","full_name":"นางสาวอุไรลักษณ์ เหล่าโก้ก","gender":"F","position":"ผู้ช่วยเจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"2","orderIndex":1783048313374},
  {"id":44,"employee_id":"4764","full_name":"นางสาวสิริวรรณ มีปาลาน","gender":"F","position":"เจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"3","orderIndex":1783048335617},
  {"id":45,"employee_id":"5754","full_name":"นางวราภรณ์ เกตุแก้ว","gender":"F","position":"ผู้ช่วยเจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"3","orderIndex":1783048361100},
  {"id":46,"employee_id":"4800","full_name":"นางสาวสุมัยพร สายเสน","gender":"F","position":"พยาบาลวิชาชีพ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"4","orderIndex":1783048429605},
  {"id":47,"employee_id":"5715","full_name":"นางสาวเดือนนภา มานะ","gender":"F","position":"ผู้ช่วยเจ้าพนักงานทะเบียน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"4","orderIndex":1783048443289},
  {"id":48,"employee_id":"4740","full_name":"นางสาวฐิติรัตน์ เสาวภาคย์กุล","gender":"F","position":"นักจัดการงานทะเบียนและบัตร","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"5","orderIndex":1783048474909},
  {"id":49,"employee_id":"4801","full_name":"นางจุฬาภรณ์ จันทศรี","gender":"F","position":"เจ้าพนักงานทันตสาธารณสุข","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"6","orderIndex":1783048801016},
  {"id":50,"employee_id":"5860","full_name":"นางอนงค์ลักษณ์ ทวียุทธศักดิ์","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"6","orderIndex":1783048844083},
  {"id":51,"employee_id":"6042","full_name":"นางธัญมาศ ศรีทอง","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"5","orderIndex":1783049078972},
  {"id":52,"employee_id":"4798","full_name":"นางจิราภรณ์ สุพล","gender":"F","position":"พยาบาลวิชาชีพ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"7","orderIndex":1783049243300},
  {"id":53,"employee_id":"4815","full_name":"นางนงลักษณ์ ล้อมวงษ์","gender":"F","position":"เจ้าพนักงานการเงินและบัญชี","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"7","orderIndex":1783049251552},
  {"id":82,"employee_id":"4796","full_name":"นางจิระวดี ผ้าลายทอง","gender":"F","position":"พยาบาลวิชาชีพ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783048047965},
  {"id":83,"employee_id":"5959","full_name":"นางสาวธเกียรติกมล ทองงอก","gender":"F","position":"ศึกษานิเทศก์","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783050640097},
  {"id":84,"employee_id":"4807","full_name":"นางธนพร กะนะหาวงศ์","gender":"F","position":"นักวิชาการคอมพิวเตอร์","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783050655073},
  {"id":85,"employee_id":"4799","full_name":"นางศินีนาฎ โสวัตร","gender":"F","position":"พยาบาลวิชาชีพ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"8","orderIndex":1783051390985},
  {"id":86,"employee_id":"5861","full_name":"นางธิดาพร โพธิ์วงศ์","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"8","orderIndex":1783051402181},
  {"id":87,"employee_id":"4790","full_name":"นางนวรัตน์ นิติเศรษฐ์","gender":"F","position":"นักวิชาการสาธารณสุข","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"9","orderIndex":1783051411135},
  {"id":88,"employee_id":"5822","full_name":"นางสาวปวันรัตน์ วิริยะกุล","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"9","orderIndex":1783051419131},
  {"id":89,"employee_id":"4735","full_name":"นางสาวณัฐฐาพร นามพิทักษ์","gender":"F","position":"เจ้าพนักงานธุรการ","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"10","orderIndex":1783051430229},
  {"id":90,"employee_id":"5734","full_name":"นางสาวภนิตา ทับบุรี","gender":"F","position":"คนงาน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"10","orderIndex":1783051443081},
  {"id":91,"employee_id":"4766","full_name":"นางจุฑาทิพย์ ยืนยง","gender":"F","position":"นักวิชาการพัสดุ","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"11","orderIndex":1783051460661},
  {"id":92,"employee_id":"5932","full_name":"นางสาวพนัชธร เทพาคำ","gender":"F","position":"คนงาน","department":"กองช่างสุขาภิบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"11","orderIndex":1783051479309},
  {"id":93,"employee_id":"4833","full_name":"นางสาวกชชัญณัช ร่วมสุข","gender":"F","position":"นักวิชาการตรวจสอบภายใน","department":"หน่วยตรวจสอบภายใน","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"12","orderIndex":1783051493213},
  {"id":94,"employee_id":"4830","full_name":"นางยุวดี ธิษาชัย","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองการเจ้าหน้าที่","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"13","orderIndex":1783051560913},
  {"id":95,"employee_id":"5820","full_name":"นางนันทวัน ศิริเทศ","gender":"F","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"13","orderIndex":1783051568792},
  {"id":96,"employee_id":"4759","full_name":"นางจตุรวัลย์ ศรีทอง","gender":"F","position":"เจ้าพนักงานการเงินและบัญชี","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"14","orderIndex":1783051579765},
  {"id":97,"employee_id":"4765","full_name":"นางปิยธิดา จันทร์เต็ม","gender":"F","position":"นักวิชาการพัสดุ","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"14","orderIndex":1783051586401},
  {"id":98,"employee_id":"4737","full_name":"นางสาวณัฐปภัสร์ ภัควลัญชณ์","gender":"F","position":"นิติกร","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"15","orderIndex":1783051600649},
  {"id":99,"employee_id":"4761","full_name":"นางสาวลิสา โคตรภักดี","gender":"F","position":"พนักงานจ้างทั่วไป","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"15","orderIndex":1783051642937},
  {"id":100,"employee_id":"4791","full_name":"นางสาวทพิดา สุยคำไฮ","gender":"F","position":"นักวิชาการสุขาภิบาล","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"16","orderIndex":1783051660079},
  {"id":101,"employee_id":"5759","full_name":"นางสาวสาวิตรี วงศ์สลับ","gender":"F","position":"คนงาน","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"16","orderIndex":1783051667961},
  {"id":102,"employee_id":"4771","full_name":"นางปวีณา ดาดก","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"17","orderIndex":1783051699077},
  {"id":103,"employee_id":"5906","full_name":"นางสาวนิธิวดี อุทธา","gender":"F","position":"ผู้ช่วยนักวิเคราะห์นโยบายและแผน","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"17","orderIndex":1783051710049},
  {"id":104,"employee_id":"4825","full_name":"นางสาวจุลมณี ทองทาบ","gender":"F","position":"นักพัฒนาชุมชน","department":"กองสวัสดิการสังคม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"18","orderIndex":1783051717903},
  {"id":105,"employee_id":"5924","full_name":"นางสาวธนิตา สายธนู","gender":"F","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"กองช่างสุขาภิบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"18","orderIndex":1783051727760},
  {"id":106,"employee_id":"4813","full_name":"นางสกุลวิไล สีลาบุตร","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"19","orderIndex":1783051735173},
  {"id":107,"employee_id":"5757","full_name":"นางสาวกนกกร อ่อนจันทร์","gender":"F","position":"ผช. จพง. จัดเก็บฯ","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"19","orderIndex":1783051745205},
  {"id":108,"employee_id":"4758","full_name":"นางสาววิภาดา คำสามารถ","gender":"F","position":"นักวิชาการเงินและบัญชี","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"20","orderIndex":1783051751146},
  {"id":109,"employee_id":"5756","full_name":"นางอรวรรณ ศรีทอง","gender":"F","position":"ผู้ช่วยเจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"20","orderIndex":1783051758381},
  {"id":110,"employee_id":"4732","full_name":"นางสาวมัญชรี จันทคล้าย","gender":"F","position":"นักจัดการงานทั่วไป","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"21","orderIndex":1783051765804},
  {"id":111,"employee_id":"5778","full_name":"นางสาวจิดาภา ล้อนันทกุล","gender":"F","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"21","orderIndex":1783051774841},
  {"id":112,"employee_id":"4802","full_name":"นางอัจจิมา บุญส่ง","gender":"F","position":"เจ้าพนักงานทันตสาธารณสุข","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"22","orderIndex":1783051784189},
  {"id":113,"employee_id":"5839","full_name":"นางอัญญาณี ศรีเสริม","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"22","orderIndex":1783051796629},
  {"id":114,"employee_id":"4779","full_name":"นางมิณรฎา แดงอุไร","gender":"F","position":"นายช่างศิลป์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"23","orderIndex":1783051844512},
  {"id":115,"employee_id":"5758","full_name":"นางสาวเบญญาภา อินทะรังษี","gender":"F","position":"คนงาน","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"23","orderIndex":1783051852229},
  {"id":116,"employee_id":"4793","full_name":"นางสาวศิริมาส สิทธิโชค","gender":"F","position":"นักวิชาการสุขาภิบาล","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"24","orderIndex":1783051863696},
  {"id":117,"employee_id":"4763","full_name":"นางจุฬาภรณ์ งามกิ่ง","gender":"F","position":"เจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"25","orderIndex":1783051951306},
  {"id":118,"employee_id":"5736","full_name":"นางสุกานดา ศรีพร","gender":"F","position":"คนงาน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"25","orderIndex":1783051962673},
  {"id":119,"employee_id":"4788","full_name":"นางสาวรภัสร์พร รุ่งสิริฤทธิเวทย์","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"26","orderIndex":1783051975685},
  {"id":120,"employee_id":"5832","full_name":"นางสาวธลิตา ทองบุราณ","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"26","orderIndex":1783051988055},
  {"id":121,"employee_id":"4743","full_name":"นางสาวอารยา สุดตลอด","gender":"F","position":"เจ้าพนักงานทะเบียน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"27","orderIndex":1783051998237},
  {"id":122,"employee_id":"5833","full_name":"นางสาวสุภารตี ส่งเสริม","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"27","orderIndex":1783052012725},
  {"id":123,"employee_id":"4770","full_name":"นางสาวสาธิกา พระอินทร์","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"28","orderIndex":1783052026633},
  {"id":124,"employee_id":"5762","full_name":"นางสาวมุกดา รุ่งเรืองงามวงค์","gender":"F","position":"คนงาน","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"28","orderIndex":1783052033596},
  {"id":125,"employee_id":"4744","full_name":"นางธัญชนก ขันเลข","gender":"F","position":"เจ้าพนักงานทะเบียน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"29","orderIndex":1783052059148},
  {"id":126,"employee_id":"5716","full_name":"นางสาววรรณวิภา วิลามาศ","gender":"F","position":"ผู้ช่วยเจ้าพนักงานทะเบียน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"29","orderIndex":1783052073934},
  {"id":127,"employee_id":"4742","full_name":"นางสาวตุลาณี ผ้าลายทอง","gender":"F","position":"เจ้าพนักงานทะเบียน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"30","orderIndex":1783052085758},
  {"id":128,"employee_id":"5717","full_name":"นางรุจิรา ไชยศิลา","gender":"F","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"30","orderIndex":1783052094017},
  {"id":129,"employee_id":"4733","full_name":"นางสาวกนิษฐา ทองคู่","gender":"F","position":"นักจัดการงานทั่วไป","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"31","orderIndex":1783052146529},
  {"id":130,"employee_id":"5937","full_name":"นางสาววรรณิศา ขวัญยืน","gender":"F","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"กองการเจ้าหน้าที่","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"31","orderIndex":1783052152597},
  {"id":131,"employee_id":"4777","full_name":"นางชลวรรณ ก้อนศิลา","gender":"F","position":"สถาปนิก","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"32","orderIndex":1783052161313},
  {"id":132,"employee_id":"5935","full_name":"นางสาวศิริพร วีระคุณ","gender":"F","position":"คนงาน","department":"กองสวัสดิการสังคม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"32","orderIndex":1783052169269},
  {"id":133,"employee_id":"4789","full_name":"นางสาวจุฑารัตน์ กะนะหาวงศ์","gender":"F","position":"นักวิชาการสาธารณสุข","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"33","orderIndex":1783052179806},
  {"id":134,"employee_id":"5864","full_name":"นางสาวสุวลี สิงห์คา","gender":"F","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"33","orderIndex":1783052186934},
  {"id":135,"employee_id":"4829","full_name":"นางนริศรา แสไพศาล","gender":"F","position":"นักทรัพยากรบุคคล","department":"กองการเจ้าหน้าที่","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"34","orderIndex":1783052193333},
  {"id":136,"employee_id":"5777","full_name":"นางสาวธารทิพย์ อุ่นทอง","gender":"F","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"34","orderIndex":1783052199750},
  {"id":137,"employee_id":"5941","full_name":"นางศิริพร พิศชาติ","gender":"F","position":"นักจัดการงานทั่วไป","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"35","orderIndex":1783052224497},
  {"id":138,"employee_id":"5923","full_name":"นางสาวลิลตา ทองบุราณ","gender":"F","position":"ผู้ช่วยนักวิชาการสุขาภิบาล","department":"กองช่างสุขาภิบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"35","orderIndex":1783052232967},
  {"id":139,"employee_id":"4734","full_name":"นางนลินี ชัยศิริกุล","gender":"F","position":"เจ้าพนักงานธุรการ","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"36","orderIndex":1783052247101},
  {"id":140,"employee_id":"4756","full_name":"นางสาวพุทธวรรณ ปทุมชาติ","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"36","orderIndex":1783052315770},
  {"id":141,"employee_id":"4809","full_name":"นางสาวธนานันต์ ปรากฏกุลทรัพย์","gender":"F","position":"นักประชาสัมพันธ์","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"37","orderIndex":1783052336237},
  {"id":142,"employee_id":"4741","full_name":"นางอริยา เชื้อทอง","gender":"F","position":"เจ้าพนักงานทะเบียน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"37","orderIndex":1783052341161},
  {"id":143,"employee_id":"4792","full_name":"นางสาวชนัญญา ศุภลักษณ์","gender":"F","position":"นักวิชาการสุขาภิบาล","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"38","orderIndex":1783052351057},
  {"id":144,"employee_id":"5908","full_name":"นางสาวชลธิชา กล่อมศิลป์","gender":"F","position":"ผู้ช่วยนักจัดการงานทั่วไป","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"38","orderIndex":1783052362985},
  {"id":146,"employee_id":"4739","full_name":"นายเกรียงไกร ณูรักษา","gender":"M","position":"นักจัดการงานทะเบียนและบัตร","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"11","orderIndex":1783053655775},
  {"id":147,"employee_id":"5755","full_name":"นายรัฐา ธานี","gender":"M","position":"ผู้ช่วยเจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"11","orderIndex":1783053696110},
  {"id":148,"employee_id":"4775","full_name":"นายชนะภัย เจริญรอย","gender":"M","position":"นายช่างโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"12","orderIndex":1783053706519},
  {"id":149,"employee_id":"5747","full_name":"นายปริญญา เหลากลม","gender":"M","position":"คนงาน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"12","orderIndex":1783053733739},
  {"id":150,"employee_id":"4832","full_name":"นายอภิชัย แก้วงาม","gender":"M","position":"เจ้าพนักงานธุรการ","department":"กองการเจ้าหน้าที่","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"13","orderIndex":1783053780484},
  {"id":151,"employee_id":"5910","full_name":"นายพรชัย บุญหวัง","gender":"M","position":"พนักงานขับรถยนต์","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"10","orderIndex":1783047414750},
  {"id":152,"employee_id":"4781","full_name":"นายอนุชิต ลำดับ","gender":"M","position":"วิศวกรไฟฟ้า","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"14","orderIndex":1783053875775},
  {"id":153,"employee_id":"5804","full_name":"นายยุรนันท์ เอิบอิ่ม","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"14","orderIndex":1783053910447},
  {"id":154,"employee_id":"4772","full_name":"นายคัชรินทร์ ทุมชาลี","gender":"M","position":"วิศวกรโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"15","orderIndex":1783053951851},
  {"id":155,"employee_id":"5803","full_name":"นายวรสิทธิ์ บุญอุ่น","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"15","orderIndex":1783053967283},
  {"id":156,"employee_id":"4757","full_name":"นายณัฐศิษฐ์ ภัทรก่อพงศ์สุข","gender":"M","position":"เจ้าพนักงานธุรการ","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"16","orderIndex":1783054006775},
  {"id":157,"employee_id":"5806","full_name":"นายนครินทร์ จันทิวา","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"16","orderIndex":1783054032187},
  {"id":158,"employee_id":"4762","full_name":"นายนิวัฒน์ คงคำลี","gender":"M","position":"เจ้าพนักงานจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"17","orderIndex":1783054056539},
  {"id":159,"employee_id":"5903","full_name":"นายสมศักดิ์ ทองศิริ","gender":"M","position":"พนักงานขับรถยนต์","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"17","orderIndex":1783054068594},
  {"id":160,"employee_id":"4782","full_name":"นายวุฒิศักดิ์ อินทอง","gender":"M","position":"นายช่างไฟฟ้า","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"18","orderIndex":1783054078371},
  {"id":161,"employee_id":"5748","full_name":"นายวสันต์ บรรพบุตร","gender":"M","position":"ผู้ช่วยนักจัดการงานทั่วไป","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"สำนักงานเทศบาล","pairNo":"18","orderIndex":1783054098654},
  {"id":162,"employee_id":"5899","full_name":"นายประยูรศักดิ์ บุญจันทร์","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"1","orderIndex":1783415192634},
  {"id":163,"employee_id":"5816","full_name":"นายเทพสถิตย์ หาสุข","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"2","orderIndex":1783059731908},
  {"id":164,"employee_id":"5812","full_name":"นายวีรยุทธ สีมั่น","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"2","orderIndex":1783059749404},
  {"id":165,"employee_id":"5809","full_name":"นายสมภพ เสมอสุข","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"3","orderIndex":1783059764223},
  {"id":166,"employee_id":"5902","full_name":"นายมนตรี คูณคำ","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"3","orderIndex":1783059790604},
  {"id":167,"employee_id":"5835","full_name":"นายอนงค์ จันทุมา","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"4","orderIndex":1783059802896},
  {"id":168,"employee_id":"5782","full_name":"นายวันชัย สุภารักษ์","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"4","orderIndex":1783059812931},
  {"id":169,"employee_id":"5789","full_name":"นายวิศรุต ไชยเดช","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"5","orderIndex":1783059846496},
  {"id":170,"employee_id":"5901","full_name":"นายสุริยา จันทร์เทศ","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"5","orderIndex":1783059869228},
  {"id":171,"employee_id":"5729","full_name":"นายสันติ ศรีทอง","gender":"M","position":"ผู้ช่วยเจ้าพนักงานเทศกิจ","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"6","orderIndex":1783059972259},
  {"id":172,"employee_id":"5868","full_name":"นายเสกศิลป์ อาภาชาติ","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"6","orderIndex":1783059980515},
  {"id":173,"employee_id":"5817","full_name":"นายบัวรินทร์ พิลาทอง","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"7","orderIndex":1783060169031},
  {"id":174,"employee_id":"5829","full_name":"นายเกรียงศักดิ์ พิณรัตน์","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"7","orderIndex":1783060260551},
  {"id":175,"employee_id":"5819","full_name":"นายยุทธนา อุ่นใจ","gender":"M","position":"ผู้ช่วยเจ้าพนักงานธุรการ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"8","orderIndex":1783060289786},
  {"id":176,"employee_id":"5851","full_name":"นายชาญศักดิ์ จันทร์แก้ว","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"8","orderIndex":1783060305179},
  {"id":177,"employee_id":"5836","full_name":"นายบุญเพ็ง ทองสัน","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"9","orderIndex":1783060319842},
  {"id":178,"employee_id":"5852","full_name":"นายพิทักษ์ แสงตาปัญ","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"9","orderIndex":1783060330319},
  {"id":179,"employee_id":"5823","full_name":"นายสันติ ศรีด้วง","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"10","orderIndex":1783060343811},
  {"id":180,"employee_id":"5874","full_name":"นายสมพงษ์ วิลาวรรณ","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"10","orderIndex":1783060353959},
  {"id":181,"employee_id":"4751","full_name":"นายนภนต์ ลีโคตร","gender":"M","position":"เจ้าพนักงานเทศกิจ","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"11","orderIndex":1783060430006},
  {"id":182,"employee_id":"5898","full_name":"นายสุรพงษ์ พันศรี","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"11","orderIndex":1783060443222},
  {"id":183,"employee_id":"5830","full_name":"นายมานัด ชุ่มเย็น","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"12","orderIndex":1783060486446},
  {"id":184,"employee_id":"5787","full_name":"นายภาคภูมิ ประทาน","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"12","orderIndex":1783060497110},
  {"id":185,"employee_id":"5858","full_name":"นายอัตถวี ป้องคำ","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"13","orderIndex":1783060546079},
  {"id":186,"employee_id":"5834","full_name":"นายสุระชัย ประทุมมา","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"13","orderIndex":1783060559770},
  {"id":187,"employee_id":"5840","full_name":"นายสุเทพ สุวรรณทอง","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"14","orderIndex":1783060571142},
  {"id":188,"employee_id":"5841","full_name":"นายวิเชษฐ์ หาสุข","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"14","orderIndex":1783060579674},
  {"id":189,"employee_id":"5773","full_name":"นายบุญประคอง ศรีสุวรรณ์","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"15","orderIndex":1783060601603},
  {"id":190,"employee_id":"5741","full_name":"นายบุญเลิศ เทศนา","gender":"M","position":"พนักงานดับเพลิง","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"15","orderIndex":1783060613934},
  {"id":191,"employee_id":"5746","full_name":"นายพัชรพงค์ โมราชาติ","gender":"M","position":"คนงาน","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"16","orderIndex":1783060624506},
  {"id":192,"employee_id":"5883","full_name":"นายรังสิมันตุ์ คุณมี","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"16","orderIndex":1783060634891},
  {"id":193,"employee_id":"5810","full_name":"นายสันติ อุทาจันทร์","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"17","orderIndex":1783060683685},
  {"id":194,"employee_id":"5784","full_name":"นายกิตติพงษ์ หงษ์ทา","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"17","orderIndex":1783060692259},
  {"id":195,"employee_id":"5877","full_name":"นายบุญหลาย ส่งเสริม","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"18","orderIndex":1783060745726},
  {"id":196,"employee_id":"5837","full_name":"นายรุ่งศักดิ์ เชื้อดวงผุย","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"18","orderIndex":1783060758339},
  {"id":197,"employee_id":"5815","full_name":"นายประเทือง วรรณคำผุย","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"1","orderIndex":1783061002018},
  {"id":198,"employee_id":"5790","full_name":"นายไพโรจน์ ใจเด็ด","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"1","orderIndex":1783061027346},
  {"id":199,"employee_id":"5896","full_name":"นายปัญญา พิมพ์วงศ์","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"2","orderIndex":1783061042962},
  {"id":200,"employee_id":"5856","full_name":"นายตวง เสนคราม","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"2","orderIndex":1783061257899},
  {"id":201,"employee_id":"4783","full_name":"นายวนล พุ่มแก้ว","gender":"M","position":"นายช่างไฟฟ้า","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"3","orderIndex":1783061265250},
  {"id":202,"employee_id":"5848","full_name":"นายสุวิทย์ หาสุข","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"3","orderIndex":1783061281456},
  {"id":203,"employee_id":"5813","full_name":"นายประดิษฐ์ บัวเขียว","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"4","orderIndex":1783061312483},
  {"id":204,"employee_id":"5869","full_name":"นายบัญชา ชอบจิตต์","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"4","orderIndex":1783061322742},
  {"id":205,"employee_id":"5818","full_name":"นายฉลอง วรพุทธ","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"5","orderIndex":1783061332658},
  {"id":206,"employee_id":"5876","full_name":"นายอภิชาติ ฟองงาม","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"5","orderIndex":1783061377313},
  {"id":207,"employee_id":"5811","full_name":"นายสมัย ฉวีรักษ์","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"6","orderIndex":1783061397466},
  {"id":208,"employee_id":"5831","full_name":"นายเสกสรร ตันตระกูล","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"6","orderIndex":1783061408394},
  {"id":209,"employee_id":"5827","full_name":"นายประสิทธิ์ ทองชุม","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"7","orderIndex":1783061418981},
  {"id":210,"employee_id":"5838","full_name":"นายสุเวช ผิวเงินยวง","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"7","orderIndex":1783061429773},
  {"id":211,"employee_id":"5842","full_name":"นายนพรัตน์ มณีโชติ","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"8","orderIndex":1783061447010},
  {"id":212,"employee_id":"5870","full_name":"นายอัตรพล บุริวัน","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"8","orderIndex":1783061463454},
  {"id":213,"employee_id":"5814","full_name":"นายธนบดี หาสุข","gender":"M","position":"พนักงานขับรถยนต์","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"9","orderIndex":1783061477959},
  {"id":214,"employee_id":"5793","full_name":"นายแมนสรวง แสงตา","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"9","orderIndex":1783061493428},
  {"id":215,"employee_id":"5862","full_name":"นายสวรรค์ บุญประสม","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"10","orderIndex":1783061509293},
  {"id":216,"employee_id":"5872","full_name":"นายประวิทย์ ช่วยรัฐ","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"10","orderIndex":1783061532300},
  {"id":217,"employee_id":"5875","full_name":"นายวิทยา บุญแปลง","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"11","orderIndex":1783061700840},
  {"id":218,"employee_id":"5879","full_name":"นายชาติชาย ไชยยิ่ง","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"11","orderIndex":1783061713342},
  {"id":219,"employee_id":"5867","full_name":"นายพีชาพล ศรีสุข","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"12","orderIndex":1783061731242},
  {"id":220,"employee_id":"5865","full_name":"นายธรรมรักษ์ ธานี","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"12","orderIndex":1783061743912},
  {"id":221,"employee_id":"5882","full_name":"นางสังวาล ขันทา","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"13","orderIndex":1783061755528},
  {"id":222,"employee_id":"5936","full_name":"นายสุรกิจ แท่งทอง","gender":"M","position":"คนงาน","department":"กองสวัสดิการสังคม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"13","orderIndex":1783061770198},
  {"id":223,"employee_id":"5740","full_name":"นายวสันต์ พรรณดวงเนตร","gender":"M","position":"พนักงานดับเพลิง","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"14","orderIndex":1783061891237},
  {"id":224,"employee_id":"5897","full_name":"นายสุรชาติ พิจารณ์","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"14","orderIndex":1783061906202},
  {"id":225,"employee_id":"5944","full_name":"นายอภินันท์ ทิพย์ราชา","gender":"M","position":"นักจัดการงานทั่วไป","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"15","orderIndex":1783061948007},
  {"id":226,"employee_id":"5878","full_name":"นายชยพจน์ โพธิภาศ","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"15","orderIndex":1783061960784},
  {"id":227,"employee_id":"5900","full_name":"นายอนุวัต ทองให้","gender":"M","position":"พนักงานขับรถยนต์ (ทั่วไป)","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"16","orderIndex":1783061973581},
  {"id":228,"employee_id":"5785","full_name":"นายอภินันท์ อุดม","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"16","orderIndex":1783061986692},
  {"id":229,"employee_id":"5774","full_name":"นายประสิทธิ์ โทนสัน","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"17","orderIndex":1783061998799},
  {"id":230,"employee_id":"5799","full_name":"นายธงชัย อารีย์เอื้อ","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"17","orderIndex":1783062018953},
  {"id":231,"employee_id":"5808","full_name":"นายสมาน บุญประสาร","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"18","orderIndex":1783062030803},
  {"id":232,"employee_id":"5859","full_name":"นายปิยพงษ์ ไชยกาล","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 3","pairNo":"18","orderIndex":1783062059675},
  {"id":233,"employee_id":"5767","full_name":"นายอำนวย ขุนทอง","gender":"M","position":"ช่างก่อสร้าง","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"1","orderIndex":1783062109133},
  {"id":234,"employee_id":"5775","full_name":"นายนริศ ทองให้","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"1","orderIndex":1783062121472},
  {"id":235,"employee_id":"5768","full_name":"นายไชยา หาระสาร","gender":"M","position":"ช่างก่อสร้าง","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"2","orderIndex":1783062155572},
  {"id":236,"employee_id":"5800","full_name":"นายยุทธนา พรมมาลุน","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"2","orderIndex":1783062178611},
  {"id":237,"employee_id":"5796","full_name":"นายสุเทพ อุดม","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"3","orderIndex":1783062189255},
  {"id":238,"employee_id":"5873","full_name":"นายอภิชาติ แสงสว่าง","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"3","orderIndex":1783062203674},
  {"id":239,"employee_id":"5797","full_name":"นายเอนก คำชมภู","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"4","orderIndex":1783062217018},
  {"id":240,"employee_id":"5781","full_name":"นายสุริยา หอกคำ","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"4","orderIndex":1783062231299},
  {"id":241,"employee_id":"5794","full_name":"นายจันที เกษเจริญคุณ","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"5","orderIndex":1783062251797},
  {"id":242,"employee_id":"5791","full_name":"นายสิทธิพร สุวะมาศ","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"5","orderIndex":1783062313061},
  {"id":243,"employee_id":"4827","full_name":"นางสาวปุณยนุช บุญเสนอ","gender":"F","position":"เจ้าพนักงานธุรการ","department":"กองสวัสดิการสังคม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"12","orderIndex":1783062957862},
  {"id":244,"employee_id":"5776","full_name":"นายวิรัตน์ อ่อนจันทร์","gender":"M","position":"ผู้ช่วยนายช่างไฟฟ้า","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"6","orderIndex":1783064471761},
  {"id":245,"employee_id":"5909","full_name":"นายปัณณทัต ทองเรือง","gender":"M","position":"คนงาน","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"6","orderIndex":1783064482933},
  {"id":246,"employee_id":"5880","full_name":"นายสดใส คัดทวี","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"7","orderIndex":1783064499986},
  {"id":247,"employee_id":"4776","full_name":"นายปรัชญวิศว์ ธานิสพงศ์","gender":"M","position":"นายช่างโยธา","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"8","orderIndex":1783064647733},
  {"id":248,"employee_id":"5714","full_name":"นายภัคนนท์ ชมภูมี","gender":"M","position":"ผู้ช่วยนักจัดการงานทั่วไป","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"8","orderIndex":1783064692117},
  {"id":249,"employee_id":"5766","full_name":"นายนคร ครองยุทธ","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"9","orderIndex":1783064701313},
  {"id":250,"employee_id":"5802","full_name":"นายสุริยา คูสิริ","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"9","orderIndex":1783064728793},
  {"id":251,"employee_id":"5765","full_name":"นายบุญมา นิลวันดี","gender":"M","position":"ช่างปูน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"10","orderIndex":1783064850228},
  {"id":252,"employee_id":"5771","full_name":"นายตะวัน พุดด้วงเงิน","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"10","orderIndex":1783064859185},
  {"id":253,"employee_id":"5763","full_name":"นายสุวิทย์ โกษาพันธ์","gender":"M","position":"ช่างไม้","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"11","orderIndex":1783064923604},
  {"id":254,"employee_id":"5805","full_name":"นายปรีชา ข้อเปี้ย","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"11","orderIndex":1783064933500},
  {"id":255,"employee_id":"5712","full_name":"นายณัฏฐ์วัฒน์ บุญสูงเนิน","gender":"M","position":"พนักงานขับรถยนต์","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"12","orderIndex":1783065855592},
  {"id":256,"employee_id":"5795","full_name":"นายบุญส่ง ปราณีศร","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"12","orderIndex":1783065868202},
  {"id":257,"employee_id":"5792","full_name":"นายไพรัตน์ ธนาเสน","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"13","orderIndex":1783065877910},
  {"id":258,"employee_id":"5807","full_name":"นายรัฐพงศ์ บุญอุ่น","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"13","orderIndex":1783065891636},
  {"id":259,"employee_id":"5769","full_name":"นายลักษณ์ โยธิน","gender":"M","position":"ช่างก่อสร้าง","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"14","orderIndex":1783065906945},
  {"id":260,"employee_id":"5786","full_name":"นายอภัยวงศ์ คำทวี","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"14","orderIndex":1783065971339},
  {"id":261,"employee_id":"5772","full_name":"นายปรีชา คำปูน","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"15","orderIndex":1783065980544},
  {"id":262,"employee_id":"5788","full_name":"นายสืบพงศ์ นิราพันธ์","gender":"M","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"15","orderIndex":1783066019272},
  {"id":263,"employee_id":"4810","full_name":"นายณัฐพล ทิพยรส","gender":"M","position":"นักประชาสัมพันธ์","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"16","orderIndex":1783066031284},
  {"id":264,"employee_id":"5798","full_name":"นายทนงศักดิ์ คำทวี","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"16","orderIndex":1783066067407},
  {"id":265,"employee_id":"5905","full_name":"นายชิษณุชา ลิ้มประเสริฐ","gender":"M","position":"ผู้ช่วยนายช่างภาพ","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"17","orderIndex":1783066082808},
  {"id":266,"employee_id":"5770","full_name":"นายมงคล ขวัญยืน","gender":"M","position":"พนักงานขับรถยนต์","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"17","orderIndex":1783066099764},
  {"id":267,"employee_id":"5846","full_name":"นายสมชาย เสมอสุข","gender":"M","position":"คนงาน","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"ศูนย์บริการสาธารณสุข แห่งที่ 2","pairNo":"1","orderIndex":1783059680557},
  {"id":268,"employee_id":"5881","full_name":"นายสมควร ภักดีบุตร","gender":"M","position":"คนงานประจำรถขยะ","department":"กองสาธารณสุขและสิ่งแวดล้อม","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"โครงการปรับปรุงคุณภาพน้ำ","pairNo":"7","orderIndex":1783492518906},
  {"id":269,"employee_id":"6045","full_name":"นางสาวมธุรดา วีระคุณ","gender":"F","position":"คนงาน","department":"กองการศึกษา","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"24","orderIndex":1783493193093},
  {"id":270,"employee_id":"5825","full_name":"นางพัชรา สุขกุล","gender":"F","position":"นักวิชาการจัดเก็บรายได้","department":"กองคลัง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"39","orderIndex":1786347375858},
  {"id":271,"employee_id":"6169","full_name":"นางสาวสุภาวดี ทองศิริ","gender":"F","position":"คนงาน","department":"กองช่าง","status":"ปฏิบัติงาน","can_duty":1,"is_inspector":0,"dutyPoint":"","pairNo":"39","orderIndex":1786347530725},
  {"id":272,"employee_id":"5945","full_name":"นางสาววรรณกานต์ หงษ์คำ","gender":"F","position":"หัวหน้าฝ่ายแผนงานและงบประมาณ","department":"กองยุทธศาสตร์และงบประมาณ","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1787645760246},
  {"id":274,"employee_id":"4731","full_name":"นางพยอม ถิรมนตรี","gender":"F","position":"หัวหน้าฝ่ายบริหารงานทั่วไป","department":"สำนักปลัดเทศบาล","status":"ปฏิบัติงาน","can_duty":0,"is_inspector":1,"dutyPoint":"","pairNo":"","orderIndex":1783047999650}
];

export const INITIAL_PERSONNEL: Personnel[] = RAW_GUARD_DATA.map((item, idx) => {
  const { fname, lname } = splitName(item.full_name);
  return {
    db_id: item.id,
    id: item.employee_id,
    fname,
    lname,
    gender: item.gender as 'M' | 'F',
    position: item.position,
    dept: item.department,
    status: 'active',
    canDuty: item.can_duty === 1,
    isInspector: item.is_inspector === 1,
    dutyPoint: item.dutyPoint || '',
    pairNo: item.pairNo || '',
    orderIndex: item.orderIndex || idx + 1,
  };
});

export const INITIAL_EMPLOYEE_DIRECTORY: EmployeeDirectoryItem[] = INITIAL_PERSONNEL.map(p => ({
  employee_id: p.id,
  full_name_thai: `${p.fname} ${p.lname}`.trim(),
  gender: p.gender,
  position_thai: p.position,
  dept: p.dept,
}));
